### ISSUE TITLE
Cannot start the react app

### ISSUE THREAD

**Issue by nishanthsinghgurung2** [micro-frontends-demo/container#38]
Hello,

I cannot start the react app by using "yarn start" command.  Further details are mentioned in the screenshot below. What am i doing wrong ?

![image](https://user-images.githubusercontent.com/64284917/152648896-050946b2-e384-4db6-9ff3-f4f48f3a2fd8.png)

**Comment by nishanthsinghgurung2** [comment]
Nvm. Had to add && in the package.json start script as follows: "SET PORT=3000 && react-app-rewired start".

However it throws another error now:


```
PS C:\Users\singnis\projects\testprojects\microfrontend-example\container> yarn start
yarn run v1.13.0
$ SET PORT=3000 && react-scripts start
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './_assignValue'
Require stack:
- C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\last-call-webpack-plugin\node_modules\lodash\assign.js
- C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\last-call-webpack-plugin\src\index.js
- C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\optimize-css-assets-webpack-plugin\src\index.js
- C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\react-scripts\config\webpack.config.js
- C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\react-scripts\scripts\start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\last-call-webpack-plugin\node_modules\lodash\assign.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\singnis\projects\testprojects\microfrontend-example\container\node_modules\last-call-webpack-plugin\src\index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\singnis\\projects\\testprojects\\microfrontend-example\\container\\node_modules\\last-call-webpack-plugin\\node_modules\\lodash\\assign.js',
    'C:\\Users\\singnis\\projects\\testprojects\\microfrontend-example\\container\\node_modules\\last-call-webpack-plugin\\src\\index.js',
    'C:\\Users\\singnis\\projects\\testprojects\\microfrontend-example\\container\\node_modules\\optimize-css-assets-webpack-plugin\\src\\index.js',
    'C:\\Users\\singnis\\projects\\testprojects\\microfrontend-example\\container\\node_modules\\react-scripts\\config\\webpack.config.js',
    'C:\\Users\\singnis\\projects\\testprojects\\microfrontend-example\\container\\node_modules\\react-scripts\\scripts\\start.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\singnis\projects\testprojects\microfrontend-example\container>
 
```

**Comment by spyder007** [comment]
@nishanthsinghgurung2 I am running into the same issue (_assignValue not found).  Did you ever figure this out?

**Comment by rileytb** [comment]
Try removing the space before `&&`. so that you end up with:

`SET PORT=3000&& react-app-rewired start`

**Comment by camjackson** [comment]
This is due to me working on mac and writing my package scripts accordingly. Try using WSL or git-bash and see if it works. Alternatively if you want to use cmd or powershell you'll need to adapt the package scripts to the proper syntax. I should have used something like cross-env but I didn't.
