### ISSUE TITLE
CORS Error on Demo Website

### ISSUE THREAD

**Issue by gitwilliam** [micro-frontends-demo/container#39]
I am receiving the following error on the live demo site: https://demo.microfrontends.com.  None of the links appear to work either.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1936859/185809311-538ee7f1-c41d-4b57-9fe6-1c475f635233.png">

This is all that is displaying:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1936859/185809330-5f6d91e1-6ce5-4934-ab88-d617c252b3af.png">

I am using Brave Browser 1.39.111 (the issue happens with the Brave shields up or down).

**Comment by camjackson** [comment]
Thanks for letting me know @gitwilliam. I just tested in Firefox and Chrome and it seems to be working for me. 

Note that CORS errors are often a red herring. It says that it can't load the script because there's no `Access-Control-Allow-Origin` header, but sometimes that's because the request is failing altogether. If it's a generic 500 response then it definitely won't have the right CORS headers, so you end up with that error in the console.

Can you have a look at the network tab, find the request for that main.[hash].js file, and let me know what it looks like? Status, headers, body, etc.

**Comment by pranavkc** [comment]
I am getting below error: 

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/pranavc/Hacking/micro-front-end/container/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
/Users/pranavc/Hacking/micro-front-end/container/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:401:16)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:433:10
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:308:13
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

**Comment by camjackson** [comment]
Closing due to inactivity.
