### ISSUE TITLE
RR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by pranavkc** [micro-frontends-demo/container#40]
Yarn install and and start is giving below error. I am using Node.js v18.13.0

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/pranavc/Hacking/micro-front-end/container/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
/Users/pranavc/Hacking/micro-front-end/container/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:401:16)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:433:10
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/webpack/lib/NormalModule.js:308:13
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/pranavc/Hacking/micro-front-end/container/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/pranavc/Hacking/micro-front-end/container/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

**Comment by camjackson** [comment]
If you google `ERR_OSSL_EVP_UNSUPPORTED`, you will find this link: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported.

From memory this error occurs when using incompatible versions of webpack and node.js. I'm not going to be updating this code any more, so if you want to run it then you probably need to use a different version of node. Have a read through the SO answers to figure out which one.
